### PR TITLE
Incorrect response expectations in cache condition directives spec fixed

### PR DESCRIPTION
**Pull request by johanandren**
Expected all headers to be filtered but just the `Range` header is filtered.

### CODE REVIEW

**Comment by ktoso** [comment]
What was the string response here?

**Comment by johanandren** [comment]
It contains the `If-Range` header as it is only the `Range` header that gets filtered.

**Comment by ktoso** [comment]
Hmm will have another look when back home, not sure I understand yet :)

**Comment by johanandren** [comment]
The test cover that `Range` is be filtered out when the `If-Range` criteria (E-tag or LastModified timestamp) does not match, and was checking that by getting extracting both `Range` and `If-Range` to produce the entity. Since `If-Range` wasn't filtered out the response entity always returned `Some(If-Range(...))` rather than `None`.

Unless, I misunderstood it and both of them should be filtered, but I couldn't see any recent change in the directive code so I guessed the test was at fault. 

Probably good if you have another look when I think about it...

**Comment by johanandren** [comment]
We need to unmerge this, I misunderstood what is going on.

**Comment by johanandren** [comment]
(sorry)

**Pull request merged**
